import type { Bucket, ClassifiedArticle, DigestCtx } from '../../shared/digest-types.js';

const SECTION_META: Array<{
  bucket: Exclude<Bucket, 'skip'>;
  heading: string;
  empty: string;
}> = [
  { bucket: 'focus', heading: '🔭 Current Focus Hits', empty: 'Nothing this cycle.' },
  { bucket: 'notable', heading: '📚 New & Notable', empty: 'Nothing this cycle.' },
  { bucket: 'followup', heading: '🔄 Follow-ups', empty: 'Nothing this cycle.' },
];

/**
 * Render the digest email as a small, email-safe HTML fragment.
 *
 * The LLM never emits HTML. We render deterministically from validated
 * classifier output and Article metadata so links always point at the original
 * collected source URL and all text is escaped before insertion.
 */
export function renderDigestEmailHtml(ctx: Pick<DigestCtx, 'date' | 'direction' | 'articles' | 'classified' | 'vault'>): string {
  const articles = ctx.articles ?? [];
  const classified = ctx.classified ?? [];
  const highlighted = classified.filter((c) => c.bucket !== 'skip').length;
  const counts = countBuckets(classified);
  const edition = ctx.direction === 'AM' ? 'Morning edition' : 'Evening edition';

  const sections = SECTION_META.map((meta) =>
    renderArticleSection(meta.heading, classified.filter((c) => c.bucket === meta.bucket), meta.empty),
  ).join('\n');

  const libraryUpdates = renderLibraryUpdates(ctx.vault?.logTail ?? '');

  return `<div style="font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 720px; margin: 0 auto; color: #1f2937; line-height: 1.5;">
  <h1 style="margin: 0 0 4px; font-size: 28px; line-height: 1.2;">🍵 Chiya Daily Digest</h1>
  <p style="color: #6b7280; margin: 0 0 16px;">${escapeHtml(ctx.date)} · ${edition}</p>

  <div style="background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 12px; padding: 12px 14px; margin: 16px 0;">
    <div style="font-size: 14px; color: #374151;"><strong>${articles.length}</strong> articles collected · <strong>${highlighted}</strong> curated highlights · graph updated before digest</div>
    <div style="font-size: 13px; color: #6b7280; margin-top: 6px;">At a glance: ${counts.focus} focus · ${counts.notable} notable · ${counts.followup} follow-up</div>
  </div>

  ${sections}

  <h2 style="font-size: 20px; margin: 24px 0 8px;">🏗️ Library Updates</h2>
  ${libraryUpdates}

  <hr style="border: 0; border-top: 1px solid #e5e7eb; margin: 24px 0 12px;">
  <p style="font-size: 12px; color: #6b7280; margin: 0;">Generated by Chiya Pasal. Article titles link to the original collected source when available.</p>
</div>`;
}

function countBuckets(classified: ClassifiedArticle[]): Record<Exclude<Bucket, 'skip'>, number> {
  return {
    focus: classified.filter((c) => c.bucket === 'focus').length,
    notable: classified.filter((c) => c.bucket === 'notable').length,
    followup: classified.filter((c) => c.bucket === 'followup').length,
  };
}

function renderArticleSection(heading: string, items: ClassifiedArticle[], emptyText: string): string {
  const body = items.length
    ? items.map(renderArticleCard).join('\n')
    : `<p style="color: #6b7280; margin: 8px 0 0;"><em>${escapeHtml(emptyText)}</em></p>`;
  return `<h2 style="font-size: 20px; margin: 24px 0 8px;">${escapeHtml(heading)}</h2>
${body}`;
}

function renderArticleCard(item: ClassifiedArticle): string {
  const article = item.article;
  const href = sourceHref(article.url);
  const title = escapeHtml(article.title);
  const titleHtml = href
    ? `<a href="${escapeAttribute(href)}" style="font-size: 16px; font-weight: 700; color: #2563eb; text-decoration: none;">${title}</a>`
    : `<strong style="font-size: 16px; color: #111827;">${title}</strong>`;
  const meta = [article.source, article.field].filter(Boolean).map((s) => escapeHtml(String(s))).join(' · ');
  const followups = item.wikilinks.length
    ? `<div style="font-size: 13px; color: #6b7280; margin-top: 4px;">Extends: ${item.wikilinks.map((w) => `<code>${escapeHtml(w)}</code>`).join(', ')}</div>`
    : '';
  const missingUrl = href ? '' : '<div style="font-size: 12px; color: #9ca3af; margin-top: 4px;">No source URL available</div>';

  return `<div style="padding: 12px 0; border-bottom: 1px solid #e5e7eb;">
  <div>${titleHtml}</div>
  <p style="margin: 6px 0 0; color: #374151;">${escapeHtml(item.reason)}</p>
  ${meta ? `<div style="font-size: 13px; color: #6b7280; margin-top: 4px;">${meta}</div>` : ''}
  ${followups}
  ${missingUrl}
</div>`;
}

function renderLibraryUpdates(logTail: string): string {
  const ingestLines = logTail
    .split('\n')
    .filter((l) => /\bingest\b/i.test(l))
    .slice(-10)
    .map((l) => l.replace(/^##\s*/, '').trim())
    .filter(Boolean);

  if (ingestLines.length === 0) {
    return '<p style="color: #6b7280; margin: 8px 0 0;"><em>No librarian activity in the recent log.</em></p>';
  }

  return `<ul style="margin: 8px 0 0; padding-left: 20px; color: #374151;">
${ingestLines.map((l) => `  <li>${escapeHtml(l)}</li>`).join('\n')}
</ul>`;
}

export function sourceHref(rawUrl: string | null | undefined): string | null {
  const url = rawUrl?.trim();
  if (!url) return null;
  if (/^https?:\/\//i.test(url)) return url;
  if (/^doi:/i.test(url)) return `https://doi.org/${url.replace(/^doi:/i, '').trim()}`;
  if (/^10\.\S+\/\S+/i.test(url)) return `https://doi.org/${url}`;
  return null;
}

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttribute(value: string): string {
  return escapeHtml(value).replace(/`/g, '&#96;');
}
